version: '3.8'

services:
  app-plan-nutricional:
    build:
      context: .
    container_name: app-plan-nutricional
    restart: unless-stopped
    networks:
      - frontend

    deploy:
      # La configuración de despliegue es específica para Docker Swarm.
      mode: replicated
      replicas: 1 # Puedes escalar el número de réplicas aquí.
      restart_policy:
        condition: on-failure
      labels:
        # --- Habilitar Traefik y configurar el Router ---
        - "traefik.enable=true"
        - "traefik.docker.network=frontend"
        - "traefik.http.routers.app-plan-nutricional.rule=Host(`plansalud.emopruebas.space`)"
        - "traefik.http.routers.app-plan-nutricional.entrypoints=websecure"
        
        # --- Configuración de TLS/SSL ---
        - "traefik.http.routers.app-plan-nutricional.tls=true"
        - "traefik.http.routers.app-plan-nutricional.tls.certresolver=le"

        # --- Configuración del Servicio ---
        - "traefik.http.services.app-plan-nutricional.loadbalancer.server.port=80"
        # ¡IMPORTANTE! Cambia '80' por el puerto que tu aplicación realmente utiliza.


networks:
  frontend:
    external: true
