version: '3.8'

services:
  app-plan-nutricional:
    image: app-plan-nutricional:latest # Es una buena práctica etiquetar la imagen
    build: .
    networks:
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        # --- Habilitar Traefik ---
        - "traefik.enable=true"
        - "traefik.docker.network=frontend"

        # --- Router HTTP ---
        - "traefik.http.routers.app-plan-nutricional.rule=Host(`plansalud.emopruebas.space`)"
        - "traefik.http.routers.app-plan-nutricional.entrypoints=websecure"
        - "traefik.http.routers.app-plan-nutricional.tls.certresolver=myresolver" # IMPORTANTE: Cambia 'myresolver' por el nombre de tu CertResolver de Let's Encrypt

        # --- Servicio ---
        - "traefik.http.services.app-plan-nutricional.loadbalancer.server.port=80"

networks:
  frontend:
    external: true
